Learn_C_sharp/ViewModels/CarsListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Shop.Data.Models;

namespace Shop.ViewModels
{
    public class CarsListViewModel
    {
        public IEnumerable<Car> allCars { get; set; }

        public string currentCategory { get; set; }
    }
}

Learn_C_sharp/ViewModels/HomeViewModel.cs
using System;
using System.Collections.Generic;
using Shop.Data.Models;

namespace Shop.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Car> favCars { get; set; }
    }
}

Learn_C_sharp/ViewModels/ShopCartViewModel.cs
using System;
using Shop.Data.Models;

namespace Shop.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart shopCart { get; set; }
    }
}

Learn_C_sharp/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.ViewModels;

// различные функции, которые будут возвращать разные View html страницы
// html ищутся функцией View в папке Views и в папке содержащий название котроллера. в данном случае Cars
namespace Shop.Controllers {
    public class CarsController : Controller { // контроллер обязательно должен наследоваться от класса Controller

        private readonly IAllCars _allCars; // создаем объект интерфейса для 
        private readonly ICarsCategory _allCategory;

        public CarsController(IAllCars iAllCars, ICarsCategory iCarsCategory) {
            _allCars = iAllCars;
            _allCategory = iCarsCategory;
        }

        [Route("Cars/List")] // при каком адресе должна срабатывать функция ниже
        [Route("Cars/List/{category}")]
        public ViewResult List(string category) //название такое же, что нужно вернуть из views cars list  
        {
            string _category = category;
            IEnumerable<Car> cars; // создаем коллекцию автомобилей
            string currentCategory = "";
            // в зависимости от url будем оперделять показать все автомобили или конкретные
            if(string.IsNullOrEmpty(category))
            {
                cars = _allCars.Cars.OrderBy(i => i.id);// показываем все автомобили
            }
            else if (string.Equals("Electro", category, StringComparison.OrdinalIgnoreCase)) 
            {
                cars = _allCars.Cars.Where(i => i.Category.categoryName.Equals("Electro"));// электрокары
                currentCategory = "Electro";
            }
            else
            {
                cars = _allCars.Cars.Where(i => i.Category.categoryName.Equals("Classic"));// классические
                currentCategory = "Classic";
            }

            // ViewBag.Category = "Some new"; // ViewBag автоматически передаются в View. Category - может быть любым названием. Some new" может быть чем угодно
            ViewBag.Title = "Страница с авто";

            var carObj = new CarsListViewModel()
            {
                allCars = cars,
                currentCategory = currentCategory
            };
            return View(carObj); // передаем в html список машин которые необходимо отобразить
        }

        // GET: /<controller>/
        //public IActionResult Index()
        //{
        //    return View();
        //}
    }
}

Learn_C_sharp/Controllers/HomeController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.Data.Repository;
using Shop.ViewModels;

namespace Shop.Controllers
{
    public class HomeController : Controller
    {
        public readonly IAllCars _carRep;

        public HomeController(IAllCars carRep)
        {
            _carRep = carRep;
        }       
            
        public ViewResult Index ()
        {
            var homeCars = new HomeViewModel
            {
                favCars = _carRep.getFavoriteCars
            };
            return View(homeCars);
        } 

    }
}

Learn_C_sharp/Controllers/OrderController.cs
// когда создаем контроллер, не забывать создавать View
using System;
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;

namespace Shop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allOrders; // для работы с базой данных
        private readonly ShopCart shopCart; // сама корзина, что в ней есть

        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }

        public IActionResult CheckOut () //возвращает Views/Order/Checkout
        {
            return View();
        }

        [HttpPost] // функция ниже вызывается когда происходит отправка данных в данном случае пользователь нажимает Finish order
        public IActionResult CheckOut(Order order) //возвращает View
        {

            shopCart.listShopItem = shopCart.getShopItems(); // берем все товары которые есть
            if(shopCart.listShopItem.Count == 0)
            {
                ModelState.AddModelError("", "Отсутсвуют товары в корзине");
            }
            else if(ModelState.IsValid) //вернет тру, только если на форме нет ошибок
            {
                allOrders.createOrder(order);
                return RedirectToAction("Complete");
            }

            return View(order); //так как View возвращаем с объектом, то поля формы будут заполнены даже после перезагрузки, например, когда по части полей ошибка
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Заказ успешно обработан";
            return View();
        }

    }
}

Learn_C_sharp/Controllers/ShopCartController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.Data.Repository;
using Shop.ViewModels;

namespace Shop.Controllers
{
    public class ShopCartController : Controller
    {
        public readonly IAllCars _carRep;
        public readonly ShopCart _shopCart;

        public ShopCartController (IAllCars carRep, ShopCart shopCart)
        {
            _carRep = carRep;
            _shopCart = shopCart;
        }

        public ViewResult Index() // возвращает шаблон
        {
            var items = _shopCart.getShopItems();
            _shopCart.listShopItem = items;

            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };

            return View(obj);
        }

        // переадресация на другую страницу
        public RedirectToActionResult addToCart(int id)
        {
            // обращаемся к хранилищу и добавляем в корзину конкретный товар (ищем по id)
            var item = _carRep.Cars.FirstOrDefault(i => i.id == id);

            if(item != null)
            {
                _shopCart.AddToCart(item); // добавление самого товара в корзину
            }

            return RedirectToAction("Index");
        }

    }
}

Learn_C_sharp/Views/Cars/List.cshtml
<!--шаблон для всех автомобилей-->
    <h1>@Model.currentCategory</h1>
    <div class="row mt-5 mb-2">
    @{
        foreach (Car car in Model.allCars) { // чтобы можно было обращаться к Model подключаем using в _ViewImports
            @Html.Partial("AllCars", car); //@Html.Partial - для подлючения шаблона, параметры какой шаблон и что в него передавать
        }
    }
    </div>

Learn_C_sharp/Views/Home/Index.cshtml
@model HomeViewModel


<h1>Лучшие автомобили</h1>
<div class="row mt-5 mb-2">
    @{
        foreach (Car car in Model.favCars)
        { // чтобы можно было обращаться к Model подключаем using в _ViewImports
            @Html.Partial("AllCars", car); //@Html.Partial - для подлючения шаблона, параметры какой шаблон и что в него передавать
        }
    }
</div>

Learn_C_sharp/Views/Order/Checkout.cshtml
@model Order

 <div class="row">
     <h3>Оформление заказа</h3>
     <form asp-action="CheckOut" method="post" class="form-horizontal">
         <div class="form-group">
             <label asp-for="name"></label>
             <div class="col-md-5">
                 <input asp-for="name" class="form-control" />
                 <span asp-validation-for="name" class="text-danger"></span>
             </div>
             </div>
             <div class="form-group">
                <label asp-for="surName"></label>
                <div class="col-md-5">
                    <input asp-for="surName" class="form-control" />
                    <span asp-validation-for="surName" class="text-danger"></span>
                </div>
             </div>
             <div class="form-group">
                 <label asp-for="adress"></label>
                 <div class="col-md-5">
                     <input asp-for="adress" class="form-control" />
                     <span asp-validation-for="adress" class="text-danger"></span>
                 </div>
                 </div>
             <div class="form-group">
                <label asp-for="phone"></label>
                <div class="col-md-5">
                    <input asp-for="phone" class="form-control" />
                    <span asp-validation-for="phone" class="text-danger"></span>
                 </div>
              </div>
              <div class="form-group">
                <label asp-for="email"></label>
                    <div class="col-md-5">
                        <input asp-for="email" class="form-control" />
                        <span asp-validation-for="email" class="text-danger"></span>
                    </div>
                </div>
         <input class="btn btn-success" type="submit" value="Finish order">
</form>
 </div>

Learn_C_sharp/Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

Learn_C_sharp/Views/Shared/AllCars.cshtml
<!--шаблон карточки автомобиля-->
@model Car

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.imgCar" alt="@Model.nameCar" />
    <h2>Model: @Model.nameCar</h2>
    <p>@Model.longDescCar</p>
    <p>Цена: @Model.priceCar.ToString("c")</p>
    <p>
        <a class="btn btn-warning" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@Model.id">Add in cart</a>
    </p>
</div>

Learn_C_sharp/Views/Shared/_Layout.cshtml
<!--общий шаблон, куда вставляем разные блоки-->
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link href="~/css/style.css" rel="stylesheet" type="text/css">
    <title>@ViewBag.Title</title>
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Carousel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List">Все автомобили</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List/Electro">Электрические</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List/Classic">Классические</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/ShopCart/">Корзина</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>

    <div class="container mt-5">
        @RenderBody() <!--сюда вставлям определнный шаблон-->
    </div>

    <footer class="container">
        <p class="float-end"><a href="#">Back to top</a></p>
        <p>© 2017–2021 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
    </footer>

    <script href="~/js/bootstrap.js"></script>
</body>
</html>

Learn_C_sharp/Views/ShopCart/Index.cshtml
@model ShopCartViewModel

<div class="container">
    @foreach (var el in Model.shopCart.listShopItem) {
        <div class="alert alert-warning mt-3">
            <b>Car: </b>@el.car.nameCar <br />
            <b>Price: </b>@el.car.priceCar.ToString("c")
        </div>
    }
    <hr />
    <a class="btn btn-danger md-5" asp-controller="Order" asp-action="Checkout">Pay</a>
</a>